/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev`/`next build`.
// It is committed here so `tsc --noEmit` works before the first build.
