// This file is automatically generated. Do not edit it directly.
// Powered by EnterCloud Managed Supabase
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spb-t4nh0v7i8379m157.supabase.opentrust.net";
const SUPABASE_PUBLISHABLE_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiIsInJlZiI6InNwYi10NG5oMHY3aTgzNzltMTU3IiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3ODM1MDU3NDQsImV4cCI6MjA5OTA4MTc0NH0.4CAMjc5Z5usnW2mt7aZLe9JzcBjkkYiTtp1xUihw4PQ";

// Exported for use in hooks that need to call Edge Functions directly (e.g. streaming AI chat)
export { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY as SUPABASE_ANON_KEY };

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
